---
- name: install uwsgi and nginx
  apt: pkg={{item}} update_cache=yes
  sudo: yes
  with_items:
      - uwsgi
      - nginx
- name: remove nginx sites-enabled/default
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: yes

- name: install needed Python packages
  apt: pkg={{item}} update_cache=yes
  sudo: yes
  with_items:
      - python3
      - uwsgi-plugin-python3
      - python3-dev
      - python-virtualenv
- name: add project user
  user: name={{project_name}} home=/projects/{{project_name}} shell=/bin/bash state=present
  sudo: yes
- name: chown user directory
  file: path=/projects/{{project_name}} owner={{project_name}}
  sudo: yes
- name: add directories
  file: path=/projects/{{project_name}}/{{item}} owner={{project_name}} state=directory
  with_items:
    - logs
    - src
    - data
    - .ssh
  sudo: yes
  sudo_user: "{{project_name}}"
- name: install requirements
  pip: extra_args="-p python3" requirements=requirements.txt virtualenv=/projects/{{project_name}}/virt/
  sudo: yes
  sudo_user: "{{project_name}}"
