---
- name: Install Open Civic Data API
  hosts: opencivicdata-api
  user: ubuntu
  sudo: yes
  roles:
      - role: common-roles/common
        hostname: ocdapi
        extra_packages:
          - libpq-dev
          - unzip
          - gdal-bin
      - role: common-roles/ebs
        device_letter: f
        volume_size: 10
        ebs_path: /projects/ocdapi/
      - role: common-roles/django
        project_name: ocdapi
        device_letter: f
        volume_size: 10
        git_repositories:
          - repo: "git://github.com/opencivicdata/api.opencivicdata.org.git"
            dir: api
          - repo: "git://github.com/opencivicdata/imago.git"
            dir: imago
        wsgi_module: ocdapi.wsgi:application
      - role: ocdapi
        project_name: ocdapi
