---
- name: Install Open Civic Data Postgres
  hosts: opencivicdata-db
  user: ubuntu
  sudo: yes
  roles:
      - role: common-roles/common
      - role: common-roles/ebs
        ebs_path: /var/lib/postgresql
        device_letter: g
        volume_size: 50
        when: use_ebs == True
      - role: common-roles/postgis
        dbuser: "ocdapi"
        dbpassword: "test"
        dbname: "ocdapi"
